### ISSUE TITLE
BR_IBGE - Testar, corrgir makefile e complementar instruções

### ISSUE THREAD

**Issue by ppKrauss** [AddressForAll/grid-tests#2]
Depois de fazer clone em ambiente com PostgrSQL,

* testar `make all0`
* fazer as devidas correções se necessário
* complementar as instruções no README

https://github.com/AddressForAll/grid-tests/blob/main/src/BR_IBGE/makefile

**Comment by crebollobr** [comment]
Sobre os targets tem no makefile all2 e all1

**Comment by ppKrauss** [comment]
Atenção, conforme https://github.com/AddressForAll/grid-tests/tree/main/src/BR_IBGE  
este git não vale mais, mudou-se para https://github.com/osm-codes/BR_IBGE#readme
