### ISSUE TITLE
Solicitar informação técnica ao IBGE sobre a grade

### ISSUE THREAD

**Issue by ppKrauss** [AddressForAll/grid-tests#3]
As principais dúvidas,  levantadas em [/src/BR_IBGE](https://github.com/AddressForAll/grid-tests/tree/main/src/BR_IBGE),  são:

* Na [estrutura original das tabelas](https://github.com/AddressForAll/grid-tests/tree/main/src/BR_IBGE#estrutura-das-tabelas), **qual o significado do campo `dom_ocu`?** 
* Na [resolução dos identificadores de célula](https://github.com/AddressForAll/grid-tests/tree/main/src/BR_IBGE#resolu%C3%A7%C3%A3o-dos-identificadores-de-c%C3%A9lula), **qual o algoritmo para determinar com precisão o identificador de célula?**<br/>Nas células de cada grade (colunas `nome_*` acima de 1km).

**Comment by luisfelipebr** [comment]
**dom_ocu** são domicílios ocupados - particulares permanentes, particulares improvisados e coletivos (todos as categorias da `V4001 - Espécie` no Censo Demográfico 2010)

**Comment by ppKrauss** [comment]
Obrigado @luisfelipebr , ReadMe atualizado com sua definição de dom_ocu!

Sobre o segundo item,  algoritmo identificador de célula, agora que atualizei para `x*10` e `y*10` na representação em *int* e *bigint*, ficou mais evidente quando que o identificador precisa de mais dígitos... Fica a dica de testar também essa hipótese.
